shrinker/urls.py
from shortener.scheduler import cron_jobs
from shortener.urls.views import url_redirect
from shortener.urls.urls import router as url_router
from shrinkers.settings import DEBUG

if DEBUG:
    import debug_toolbar
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from ninja import NinjaAPI
from shortener.users.apis import user as user_router

schema_view = get_schema_view(
    openapi.Info(
        title="Shrinkers API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

apis = NinjaAPI(title="Shrinkers API")
apis.add_router("/users/", user_router, tags=["Users"])

urlpatterns = [
    url(r"^swagger(?P<format>\.json|\.yaml)$", schema_view.without_ui(cache_timeout=0), name="schema-json"),
    url(r"^swagger/$", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    url(r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("admin/", admin.site.urls),
    path("", include("shortener.index.urls")),
    path("urls/", include("shortener.urls.urls")),
    path("admins/", include("shortener.admins.urls")),
    path("api/", include(url_router.urls)),
    path("ninja-api/", apis.urls),
    path("<str:prefix>/<str:url>", url_redirect),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),  # Django Debug Tool
    ]

cron_jobs()

shortener/models.py
import string
import random
from typing import Dict

from django.db import models
from django.contrib.auth.models import User as U
from django.db.models.base import Model
from shortener.model_utils import dict_filter, dict_slice, location_finder

# Create your models here.


class TimeStampedModel(models.Model):
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class PayPlan(TimeStampedModel):
    name = models.CharField(max_length=20)
    price = models.IntegerField()


class Organization(TimeStampedModel):
    class Industries(models.TextChoices):
        PERSONAL = "personal"
        RETAIL = "retail"
        MANUFACTURING = "manufacturing"
        IT = "it"
        OTHERS = "others"

    name = models.CharField(max_length=50)
    industry = models.CharField(max_length=15, choices=Industries.choices, default=Industries.OTHERS)
    pay_plan = models.ForeignKey(PayPlan, on_delete=models.DO_NOTHING, null=True)


class Users(models.Model):
    user = models.OneToOneField(U, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100, null=True)
    telegram_username = models.CharField(max_length=100, null=True)
    url_count = models.IntegerField(default=0)
    organization = models.ForeignKey(Organization, on_delete=models.DO_NOTHING, null=True)


class EmailVerification(TimeStampedModel):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    key = models.CharField(max_length=100, null=True)
    verified = models.BooleanField(default=False)


class Categories(TimeStampedModel):
    name = models.CharField(max_length=100)
    organization = models.ForeignKey(Organization, on_delete=models.DO_NOTHING, null=True)
    creator = models.ForeignKey(Users, on_delete=models.CASCADE)


def rand_string():
    str_pool = string.digits + string.ascii_letters
    return ("".join([random.choice(str_pool) for _ in range(6)])).lower()


def rand_letter():
    str_pool = string.ascii_letters
    return random.choice(str_pool).lower()


class ShortenedUrls(TimeStampedModel):
    class UrlCreatedVia(models.TextChoices):
        WEBSITE = "web"
        TELEGRAM = "telegram"

    nick_name = models.CharField(max_length=100)
    category = models.ForeignKey(Categories, on_delete=models.DO_NOTHING, null=True)
    prefix = models.CharField(max_length=50, default=rand_letter)
    creator = models.ForeignKey(Users, on_delete=models.CASCADE)
    target_url = models.CharField(max_length=2000)
    click = models.BigIntegerField(default=0)
    shortened_url = models.CharField(max_length=6, default=rand_string)
    create_via = models.CharField(max_length=8, choices=UrlCreatedVia.choices, default=UrlCreatedVia.WEBSITE)
    expired_at = models.DateTimeField(null=True)

    class Meta:
        indexes = [
            models.Index(
                fields=[
                    "prefix",
                    "shortened_url",
                ]
            ),
        ]

    def clicked(self):
        self.click += 1
        self.save()
        return self


class Schedules(TimeStampedModel):
    job_name = models.CharField(max_length=50)
    flag_name = models.CharField(max_length=50)
    value = models.IntegerField(default=0)


class Statistic(TimeStampedModel):
    class ApproachDevice(models.TextChoices):
        PC = "pc"
        MOBILE = "mobile"
        TABLET = "tablet"

    shortened_url = models.ForeignKey(ShortenedUrls, on_delete=models.CASCADE)
    ip = models.CharField(max_length=15)
    web_browser = models.CharField(max_length=50)
    device = models.CharField(max_length=6, choices=ApproachDevice.choices)
    device_os = models.CharField(max_length=30)
    country_code = models.CharField(max_length=2, default="XX")
    country_name = models.CharField(max_length=100, default="UNKNOWN")
    custom_params = models.JSONField(null=True)

    def record(self, request, url: ShortenedUrls, params: Dict):
        self.shortened_url = url
        self.ip = request.META["REMOTE_ADDR"]
        self.web_browser = request.user_agent.browser.family
        self.device = (
            self.ApproachDevice.MOBILE
            if request.user_agent.is_mobile
            else self.ApproachDevice.TABLET
            if request.user_agent.is_tablet
            else self.ApproachDevice.PC
        )
        self.device_os = request.user_agent.os.family
        t = TrackingParams.get_tracking_params(url.id)
        if params:
            self.custom_params = dict_slice(dict_filter(params, t), 5)

        try:
            country = location_finder(request)
            self.country_code = country.get("country_code", "XX")
            self.country_name = country.get("country_name", "UNKNOWN")
        except:
            pass

        url.clicked()
        self.save()


class TrackingParams(TimeStampedModel):
    shortened_url = models.ForeignKey(ShortenedUrls, on_delete=models.CASCADE)
    params = models.CharField(max_length=20)

    @classmethod
    def get_tracking_params(cls, shortened_url_id:int):
        return TrackingParams.objects.filter(shortened_url_id=shortened_url_id).values_list("params", flat=True)


class BackOfficeLogs(TimeStampedModel):
    endpoint = models.CharField(max_length=2000, blank=True, null=True)
    body = models.JSONField(null=True)
    method = models.CharField(max_length=20, blank=True, null=True)
    user_id = models.IntegerField(blank=True, null=True)
    ip = models.CharField(max_length=30, blank=True, null=True)
    status_code = models.IntegerField(blank=True, null=True)


class DailyVisitors(models.Model):
    visit_date = models.DateField()
    visits = models.IntegerField(default=0)
    totals = models.IntegerField(default=0)
    last_updated_on = models.DateTimeField(auto_now=True)


class JobInfo(TimeStampedModel):
    class JOB_STATUS(models.TextChoices):
        WAIT = "wait"
        RUN = "run"
        OK = "ok"
        ERROR = "error"
    job_id = models.CharField(max_length=255)
    user_id = models.IntegerField(null=True)
    additional_info = models.JSONField(null=True)
    status = models.CharField(max_length=6, choices=JOB_STATUS.choices, default=JOB_STATUS.WAIT)

templates/admin_url_list.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}
{% block title %}URL 리스트{% endblock %}
{% block main_breadscumb %}대시 보드{% endblock %}
{% block sub_breadscumb_highlight %}URL List{% endblock %}
{% block sub_breadscumb %}URL 리스트{% endblock %}
{% block content %}

    <div class="row" id="vue_div">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-header border-0">
                    <a href="{% url 'url_create' %}" class="btn btn-primary btn-sm font-size-12 float-right">
                        추가
                    </a>
                </div>
                <div class="table-responsive">
                    <!-- Projects table -->
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light text-center">
                        <tr>
                            <th rowspan='2'>별칭</th>
                            <th scope="col">이동 URL</th>
                            <th scope="col">단축 URL</th>
                            <th scope="col">생성 채널</th>
                            <th scope="col">생성일</th>
                            <th scope="col">클릭수</th>
                            <th rowspan='2'>액션</th>
                        </tr>
                        <tr>
                            <th scope="col">생성자(이메일)</th>
                            <th scope="col">텔레 그램 ID</th>
                            <th scope="col">소속</th>
                            <th scope="col">페이 플랜</th>
                            <th scope="col">엣지 사용 수</th>
                        </tr>

                        </thead>
                        <tbody>
                        {% for u in urls %}
                            <tr>
                                <th class="font-weight-bold" rowspan="2">{{ u.nick_name }}</th>

                                <td>{{ u.target_url }} </td>
                                <td>
                                    <a href="/{{ u.prefix }}/{{ u.shortened_url }}" target="_blank">
                                        {{ request.get_protocol }}{{ request.get_host }}/{{ u.prefix }}/{{ u.shortened_url }}
                                    </a>
                                </td>
                                <td>{{ u.create_via }}</td>
                                <td>{{ u.created_at | date:"Y-m-d" }}</td>
                                <td>
                                    {{ u.click }}
                                    <a href="{% url 'statistic_view' url_id=u.id %}">
                                        <i class="ni ni-chart-bar-32 ml-2" style="cursor: pointer;"></i>
                                    </a>
                                </td>
                                <td rowspan="2">
                                    <a class="btn btn-sm btn-primary text-white"
                                       href="{% url 'url_change' action='update' url_id=u.id %}">
                                        수정
                                    </a>
                                    <button @click="deleteUrl({{ u.id }})" class="btn btn-sm btn-danger">
                                        삭제
                                    </button>
                                </td>
                            </tr>
                            <tr>
                                <td scope="col">{{ u.creator.full_name }} ({{ u.creator.user.email }})</td>
                                <td scope="col">{{ u.creator.telegram_username }}</td>
                                <td scope="col">{{ u.creator.organization.name }}</td>
                                <td scope="col">{{ u.creator.organization.pay_plan.name }}</td>
                                {% comment %} <td scope="col">{{ u.statistic_set.all | get_count:"web_browser,Edge" }} 개</td> {% endcomment %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script>
        let vm = new Vue({
            delimiters: ['[[', ']]'],
            el: '#vue_div',
            data: {
                newUrlName: null,
                newUrlTarget: null,
                urlLists: []
            },
            mounted() {
            },
            methods: {
                deleteUrl: function (urlId) {
                    const c = confirm('정말 삭제 하시겠습니까?');
                    if (!c) return;
                    axios.delete(`/api/urls/${urlId}`, {headers: {'X-CSRFToken': Cookies.get('csrftoken')}}
                    ).then(function (response) {
                    }).catch(function (e) {
                    }).finally(function () {
                        window.location.reload();
                    });
                }
            },
            filters: {
                addressAssembler: function (v, arg) {
                    const url = new URL(document.URL);
                    const host = url.host;
                    return `${host}/${v}/${arg}`
                }
            }
        })
    </script>
{% endblock %}

templates/base.html
{% load static %}

<!--

=========================================================
* Impact Design System - v1.0.0
=========================================================

* Product Page: https://www.creative-tim.com/product/impact-design-system
* Copyright 2010 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://github.com/creativetimofficial/impact-design-system/blob/master/LICENSE.md)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

-->
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8"/>
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta
            name="description"
            content="Start your development with a Dashboard for Bootstrap 4."
    />
    <meta name="author" content="Creative Tim"/>
    <title>{% block title %}{% endblock %} | Shrinkers</title>

    <!-- Fonts -->
    <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700"
    />
    <!-- Icons -->
    <link
            rel="stylesheet"
            href="{% static 'assets/vendor/nucleo/css/nucleo.css' %}"
            type="text/css"
    />
    <link
            rel="stylesheet"
            href="{% static 'assets/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}"
            type="text/css"
    />
    <!-- Page plugins -->
    <link
            rel="stylesheet"
            href="{% static 'assets/vendor/fullcalendar/dist/fullcalendar.min.css' %}"
    />
    <link
            rel="stylesheet"
            href="{% static 'assets/vendor/sweetalert2/dist/sweetalert2.min.css' %}"
    />
    <link
            rel="stylesheet"
            href="//cdn.datatables.net/1.11.0/css/jquery.dataTables.min.css"
    />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Argon CSS -->
    <link
            rel="stylesheet"
            href="{% static 'css/dashboard.css' %}"
            type="text/css"
    />
    <!-- Core -->
    <script src="{% static 'assets/vendor/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/js-cookie/js.cookie.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}"></script>
    <!-- Optional JS -->
    <script src="{% static 'assets/vendor/chart.js/dist/Chart.min.js' %}"></script>
    <script src="{% static 'assets/vendor/chart.js/dist/Chart.extension.js' %}"></script>
    <script src="//cdn.datatables.net/1.11.0/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.7/dist/loadingoverlay.min.js"></script>
    <script src="{% static 'assets/js/dashboard.js' %}?v=1.2.0"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-206174703-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-206174703-1');
    </script>

</head>

<body>
{% include 'includes/nav.html' %}
<!-- Main content -->
<div class="main-content" id="panel">
    <!-- Topnav -->
    {% include 'includes/top_nav.html' %}
    <!-- Header -->
    <!-- Header -->
    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">
                            {% block sub_breadscumb_highlight %}{% endblock %}</h6>
                        <nav
                                aria-label="breadcrumb"
                                class="d-none d-md-inline-block ml-md-4"
                        >
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                <li class="breadcrumb-item">
                                    <a href="#">
                                        {% block main_breadscumb %}{% endblock %}
                                    </a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    {% block sub_breadscumb %}{% endblock %}
                                </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--6">
        {% block content %}
        {% endblock %}
    </div>
</div>
<!-- Argon JS -->

<!-- Demo JS - remove this in your project -->
<script src="{% static 'assets/js/dashboard.js' %}?v=1.2.0"></script>
<script src="{% static 'assets/js/demo.min.js' %}"></script>
</body>

</html>

templates/boards.html
{% extends "base.html" %}
{% load custom_tags %}
{% block content %}
    <h2>유저 리스트</h2>
    <h4>{% if msg %}{{ msg }}{% endif %}</h4>
    <table class="table table-bordered">
        <thead>
        <th>ID</th>
        <th>유저이름</th>
        <th>이메일</th>
        <th>가입일</th>
        <th>페이플랜</th>
        <th>가격</th>
        </thead>
        {% for u in users %}
            <tr class={% cycle "table-dark" "" %}>
                <td>{{ u.id }}</td>
                <td>{{ u.username }}</td>
                <td>{{ u.email|email_ma:u.id }}</td>
                <td>{{ u.date_joined }}</td>
                <td>{{ u.pay_plan.name }}</td>
                <td>{{ u.pay_plan.price }}</td>
            </tr>
        {% endfor %}
    </table>


    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if users.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?p={{ users.previous_page_number }}">이전으로</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="#">이전으로</a>
                </li>
            {% endif %}
            <li class="page-item">
                <a class="page-link"
                   href="?p={{ users.number|add:1 }}">{{ users.number }}/{{ users.paginator.num_pages }}</a>
            </li>
            {% if users.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?p={{ users.next_page_number }}">다음으로</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="#">다음으로</a>
                </li>
            {% endif %}
        </ul>
    </nav>
    <p>
        <a href="{% url 'index' %}">홈으로</a>
        <a href="{% url 'register' %}">회원가입</a>
    </p>
    {% test_tags %}
    {% include "include_test.html" %}
{% endblock %}

templates/login.html
{% load static %}
<!--

=========================================================
* Impact Design System - v1.0.0
=========================================================

* Product Page: https://www.creative-tim.com/product/impact-design-system
* Copyright 2010 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://github.com/creativetimofficial/impact-design-system/blob/master/LICENSE.md)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

-->
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
    <meta name="author" content="Creative Tim">
    <title>Impact Dashboard - Login</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <!-- Icons -->
    <link rel="stylesheet" href="{% static 'assets/vendor/nucleo/css/nucleo.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}"
          type="text/css">
    <!-- Page plugins -->
    <link rel="stylesheet" href="{% static 'assets/vendor/fullcalendar/dist/fullcalendar.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendor/sweetalert2/dist/sweetalert2.min.css' %}">
    <!-- Argon CSS -->
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}" type="text/css">

</head>


<body class="bg-white">
<!-- Main content -->
<div class="main-content">
    <!-- Header -->
    <div class="header bg-gradient-primary py-7 py-lg-8 pt-lg-9">
        <div class="container">
            <div class="header-body text-center mb-7">
                <div class="row justify-content-center">
                    <div class="col-xl-5 col-lg-6 col-md-8 px-5">
                        <h1 class="text-white">로그인</h1>
                        <p class="text-lead text-white">Shrinkers에 오신것을 환영합니다.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="separator separator-bottom separator-skew zindex-100">
            <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1"
                 xmlns="http://www.w3.org/2000/svg">
                <polygon class="fill-white" points="2560 0 2560 100 0 100"></polygon>
            </svg>
        </div>
    </div>
    <!-- Page content -->
    <div class="container mt--9 pb-5 text-gray">
        <div class="row justify-content-center">
            <div class="col-lg-5 col-md-7">
                <div class="card bg-secondary border border-soft mb-0">
                    <div class="card-header bg-transparent pb-5">
                        <div class="text-center mt-2 mb-3"><small>소셜로 로그인 하기</small></div>
                        <div class="btn-wrapper text-center">
                            <a href="#" class="btn btn-neutral btn-icon">
                                <span class="btn-inner--icon"><img
                                        src="{% static 'assets/img/icons/common/github.svg' %}"></span>
                                <span class="btn-inner--text">Github</span>
                            </a>
                            <a href="#" class="btn btn-neutral btn-icon">
                                <span class="btn-inner--icon"><img
                                        src="{% static 'assets/img/icons/common/google.svg' %}"></span>
                                <span class="btn-inner--text">Google</span>
                            </a>
                        </div>
                    </div>
                    <div class="card-body px-lg-5 py-lg-5">
                        <div class="text-center mb-4">
                            <small>이메일 로그인</small>
                        </div>
                        {% if msg %}
                            <p class="text-center text-sm text-danger">{{ msg }}</p>
                        {% endif %}
                        {% if is_ok or user.is_authenticated %}
                            <p class="text-center text-sm text-success">로그인 성공({{ user.username }}) <a
                                    class="text-primary" href="{% url 'logout' %}">로그아웃</a></p>
                        {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group mb-3">
                                <div class="input-group input-group-merge input-group-alternative">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="ni ni-user-run"></i></span>
                                    </div>
                                    {{ form.email }}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group input-group-merge input-group-alternative">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                                    </div>
                                    {{ form.password }}
                                </div>
                            </div>
                            <div class="custom-control custom-control-alternative custom-checkbox">
                                {{ form.remember_me }}
                                <label class="custom-control-label" for="_loginRememberMe">
                                    <span>로그인 유지하기</span>
                                </label>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary my-4">로그인</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-6">
                        <a href="#" class="text-gray"><small>비밀번호 찾기</small></a>
                    </div>
                    <div class="col-6 text-right">
                        <a href="{% url 'register' %}" class="text-gray"><small>회원가입</small></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Argon Scripts -->
<!-- Core -->
<script src="{% static 'assets/vendor/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/js-cookie/js.cookie.js' %}"></script>
<script src="{% static 'assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}"></script>
<script src="{% static 'assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}"></script>
<!-- Argon JS -->
<script src="{% static 'assets/js/dashboard.js' %}?v=1.2.0"></script>
<!-- Demo JS - remove this in your project -->
<script src="{% static 'assets/js/demo.min.js' %}"></script>
</body>

</html>

templates/url_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}단축 URL 생성{% endblock %}
{% block sub_breadscumb %}URL 생성{% endblock %}
{% block main_breadscumb %}URL 리스트{% endblock %}
{% block sub_breadscumb_highlight %}단축 URL {% endblock %}
{% block content %}

    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        {% if is_update %}
                            <h3>{{ form.nick_name.value }} 수정하기</h5>
                        {% else %}
                            <h3>단축 URL 만들기</h5>
                        {% endif %}
                    </div>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="row">
                            {% for f in form.visible_fields %}
                                <div class="col-6">
                                    <label>{{ f.label }}</label>
                                    {{ f }}
                                </div>
                            {% endfor %}
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-success mt-5">
                                {% if is_update %}
                                    {{ form.nick_name.value }} 수정
                                {% else %}
                                    생성
                                {% endif %}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}